### ISSUE TITLE
 'html-webpack-plugin-before-html-processing'. Hook was not found.

### ISSUE THREAD

**Issue by liam33893** [GoogleChromeLabs/preload-webpack-plugin#119]
I just added the plugin to the webpack config:
```javascript
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new MiniCssExtractPlugin({
      filename: 'styles.css',
    }),
    new HtmlWebpackPlugin({
      inject: true,
      favicon: './public/favicon.ico',
      template: './public/index.html',
    }),
    new PreloadWebpackPlugin(),
    new ForkTsCheckerWebpackPlugin({
      typescript: {
        diagnosticOptions: {
          semantic: true,
          syntactic: true,
        },
      },
    }),
  ],
```
and got errors:
```log
> webpack-dev-server --progress --colors --open
Error: Plugin could not be registered at 'html-webpack-plugin-before-html-processing'. Hook was not found.
BREAKING CHANGE: There need to exist a hook at 'this.hooks'. To create a compatibility layer for this hook, hook into 'this._pluginCompat'.
    at Compilation.plugin (D:\repos\test-1\node_modules\tapable\lib\Tapable.js:69:9)
    at Compilation.deprecated [as plugin] (internal/util.js:67:15)
    at D:\repos\test-1\node_modules\preload-webpack-plugin\index.js:64:19
    at SyncHook.eval [as call] (eval at create (D:\repos\test-1\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:11:1)
    at SyncHook.lazyCompileHook (D:\repos\test-1\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.newCompilation (D:\repos\test-1\node_modules\webpack\lib\Compiler.js:631:26)
    at D:\repos\test-1\node_modules\webpack\lib\Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\repos\test-1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (D:\repos\test-1\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.compile (D:\repos\test-1\node_modules\webpack\lib\Compiler.js:662:28)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```
I use all latest versions for webpack and plugins.

Thanks for the help

**Comment by toxic-johann** [comment]
Have you tried the V3?

**Comment by liam33893** [comment]
`"preload-webpack-plugin": "^3.0.0-beta.4",`

Thanks that helped! It works
